//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudioByPhoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompletedWork
    {
        public int IdCompletedWork { get; set; }
        public int IdOrder { get; set; }
        public int IdFormat { get; set; }
        public byte[] File { get; set; }
    
        public virtual FileFormat FileFormat { get; set; }
        public virtual Order Order { get; set; }
    }
}
