//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudioByPhoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileFormat
    {
        public FileFormat()
        {
            this.CompletedWork = new HashSet<CompletedWork>();
        }
    
        public int IdFormat { get; set; }
        public string Expansion { get; set; }
    
        public virtual ICollection<CompletedWork> CompletedWork { get; set; }
    }
}
