//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudioByPhoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.CompletedWork = new HashSet<CompletedWork>();
            this.ServiceOrder = new HashSet<ServiceOrder>();
            this.StudioOrder = new HashSet<StudioOrder>();
        }
    
        public int IdOrder { get; set; }
        public int IdService { get; set; }
        public int IdCustomer { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<int> IdDiscount { get; set; }
        public Nullable<decimal> FinalPrice { get; set; }
        public int IdWorker { get; set; }
    
        public virtual ICollection<CompletedWork> CompletedWork { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Discount Discount { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual ICollection<ServiceOrder> ServiceOrder { get; set; }
        public virtual ICollection<StudioOrder> StudioOrder { get; set; }
    }
}
