//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudioByPhoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Photo
    {
        public int IdPhoto { get; set; }
        public int IdWorker { get; set; }
        public string PhotoUrl { get; set; }
    
        public virtual Worker Worker { get; set; }
    }
}
