//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudioByPhoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Service
    {
        public Service()
        {
            this.ServiceOrder = new HashSet<ServiceOrder>();
        }
    
        public int IdService { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public string Descriotion { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual ICollection<ServiceOrder> ServiceOrder { get; set; }
    }
}
