//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudioByPhoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studio
    {
        public Studio()
        {
            this.StudioOrder = new HashSet<StudioOrder>();
        }
    
        public int IdStudio { get; set; }
        public string Address { get; set; }
        public string Name { get; set; }
        public decimal Price { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual ICollection<StudioOrder> StudioOrder { get; set; }
    }
}
