//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudioByPhoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudioOrder
    {
        public int IdStudioOrder { get; set; }
        public int IdStudio { get; set; }
        public int IdOrder { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Studio Studio { get; set; }
    }
}
