//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudioByPhoto
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StudioByPhotoEntities : DbContext
    {
        public StudioByPhotoEntities()
            : base("name=StudioByPhotoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CompletedWork> CompletedWork { get; set; }
        public DbSet<Customer> Customer { get; set; }
        public DbSet<Discount> Discount { get; set; }
        public DbSet<FileFormat> FileFormat { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<Photo> Photo { get; set; }
        public DbSet<Position> Position { get; set; }
        public DbSet<Service> Service { get; set; }
        public DbSet<ServiceOrder> ServiceOrder { get; set; }
        public DbSet<Studio> Studio { get; set; }
        public DbSet<StudioOrder> StudioOrder { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<Worker> Worker { get; set; }
    }
}
