//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudioByPhoto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public Worker()
        {
            this.Order = new HashSet<Order>();
            this.Photo1 = new HashSet<Photo>();
        }
    
        public int IdWorker { get; set; }
        public int IdPosition { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
        public string Patronymic { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Passport { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public int IdRole { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual ICollection<Order> Order { get; set; }
        public virtual ICollection<Photo> Photo1 { get; set; }
        public virtual Position Position { get; set; }
    }
}
